### PR TITLE
Synchronizing PlatformIO and XMC4Arduino Versions

### PR DESCRIPTION
**Pull request by LinjingZhang**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Synchronizing PlatformIO and XMC4Arduino Versions: gcc toolchain and library version

Related Issue
https://github.com/Infineon/platformio-infineonxmc/issues/19

Context
Quick update to synchronizing PlatformIO and XMC4Arduino Versions. 
Further updates required (package registry, boards json...)

### CODE REVIEW

**Comment by LinjingZhang** [comment]
ok It looks like we removed some of the target board, so we need to modify the CICD 😺

**Comment by ederjc** [comment]
Yes, the board list also needs to be synced with XMC for Arduino (see https://github.com/Infineon/platformio-infineonxmc/tree/master/boards)

Also it looks like the examples need to be updated. Maybe they can also be removed?

**Comment by LinjingZhang** [comment]
> Yes, the board list also needs to be synced with XMC for Arduino (see https://github.com/Infineon/platformio-infineonxmc/tree/master/boards)
> 
> Also it looks like the examples need to be updated. Maybe they can also be removed?

I did not add all boards, but removed unsupported boards.
I want to keep the example tests as much as possible, I removed the unsupported target and the rest passed.

**Review by jaenrig-ifx — APPROVED** [review]
Make sense that all not supported boards and examples are removed. If the metafiles changes requires are sufficient or not I can´t judge :) 
But it looks green now.

**Review by ederjc — APPROVED** [review]

**Pull request merged**
